# Use this file to build and test the objects using your 
# installation of CppUnit you've aquired from SourceForge. 
# Then you'll need to do is set the CPPROOT path. 


LD_LIBRARY_PATH=${CPPROOT}/src/cppunit/.libs
LIBS=-lcppunit -ldl
CPPINCLUDES=-I${CPPROOT}/include
LIBDIR=${CPPINCLUDES} -L${CPPROOT}/src/cppunit/.libs
objects = main.o \
 FixedPoint.o \
 FixedPointTest.o \
 Parser.o \
 ParserTest.o \

CXXFLAGS= -g ${CPPINCLUDES} -DCPPTESTING
TAGS=$(shell ls *.cpp)

aal : $(objects)
	g++  $(objects) -g -o aal -DDEBUG ${LIBS} ${LIBDIR}

main.o:	

.PHONY : clean
clean :
	rm aal $(objects) 


test: aal TAGS
	export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}; ./aal test	

TAGS:	${TAGS}   
	echo "making tags..."
	etags ${TAGS}
